### DISCUSSION TITLE
User filters aka "My filters" in uBlock Origin Lite for Safari

### DISCUSSION THREAD

**Discussion by mrp714** [uBlockOrigin/uBOL-home#372] [Ideas]
Hello gorhill,

Having tested out uBOL in Safari I noticed it doesn't have support for user specific filters. I use this feature in uBO in Firefox a lot for personal tweaks on sites, for example on reddit I have the following to remove a few things I don't care for. 

```
reddit.com##.redesign-beta-optin
reddit.com##.initialized.listing-chooser
reddit.com##.premium-banner
old.reddit.com###eu-cookie-policy
old.reddit.com##.happening-now
```

This works well in AdGuard for Safari via their "user rules" filter which is essentially the same thing as in regular uBO "My filters". 

It would be excellent if this could be added to uBOL for Safari at some point in the future as it would enable me to then drop the need for AdGuard for Safari 👍

Many thanks as always for all your hard work in making the web actually usable.

**Comment by gorhill** [comment]
https://github.com/uBlockOrigin/uBOL-home/issues/325

**Reply by mrp714** [reply]
Hi Raymond,

While the element zapper does indeed remove the element it does not persist on page reload. Should it? 

Or am I missing something mention in #325 ? 

Are user filters unable to added to uBOL for Safari for technical reasons? 

My apologies if I am missing something obvious, I have had a search through the issue tracker, etc. but couldn't find a clear answer hence this feature request. 

I [perhaps wrongly] assumed that as AdGuard for Safari supports user filters it may be possible for uBOL to also support them too.

**Reply by stephenhawk8054** [reply]
The title of that thread is

> Bring back element picker in a limited form

Element picker, not element zapper

**Reply by mrp714** [reply]
Okay so following that thread through to a comment also by you https://github.com/uBlockOrigin/uBOL-home/issues/269#issuecomment-2606639147 

> uBOL does not support custom filters.

My apologies if this is clearly answered elsewhere but I can't seem to find a definitive answer - will custom filters be added at some point? I see Raymond discuss a possible solution but it is not clear if this is something being worked on or if it was just an idea he had.

**Reply by mapx-** [reply]
The custom filters (_rules_) are already implemented.
Enable the feature in uBOL settings ("developer mode"), then go into "develop" tab and add the rule.

The rules are not the classic uBO filters but in DNR format:
https://github.com/gorhill/uBlock/commit/9339a75952

examples (rules separated by `---`):

```
action:
  type: block
condition:
  urlFilter: ||[526d43cc6c.com](http://526d43cc6c.com/)^
---
action:
  redirect:
    url: https://cdn.jsdelivr.net/gh/uBlockOrigin/uBOL-home/chromium/web_accessible_resources/noop.js
  type: redirect
condition:
  initiatorDomains:
    - 216.219.94.112
  resourceTypes:
    - script
  urlFilter: ||[poweredby.jads.co/js/jads.js](http://poweredby.jads.co/js/jads.js)
```
